### ISSUE TITLE
Case when Different Security Context is used for request decryption and response encryption

### ISSUE THREAD

**Issue by rikard-sics** [core-wg/oscore-key-update#58]
Add text on generic considerations for when changing the security context between request decryption and response encryption (in section 2.3.1).

Can take inspiration from Group OSCORE draft:
_In step 3, if the server is using a different Security Context for the response compared to what was used to verify the request (see [Section 3.2](https://datatracker.ietf.org/doc/html/draft-ietf-core-oscore-groupcomm-15#section-3.2)), then the server MUST include its Sender Sequence Number as Partial IV in the response and use it to build the AEAD nonce to protect the response. This prevents the AEAD nonce from the request from being reused._
https://datatracker.ietf.org/doc/html/draft-ietf-core-oscore-groupcomm-15#section-8.3

Also add a specific note that server should include PIV in Response 2 for KUDOS.

**Comment by rikard-sics** [comment]
This is something to mention in the KUDOS draft, another point that updates OSCORE.

**Comment by marco-tiloca-sics** [comment]
Closed by https://github.com/core-wg/oscore-key-update/commit/645a6d80866d54c2552d8c01ff0838be5c343b96
