### ISSUE TITLE
Enforce including Partial IV in KUDOS message 2 for client-initiated version (and general considerations for OSCORE)

### ISSUE THREAD

**Issue by rikard-sics** [core-wg/oscore-key-update#63]
Meaning Response 1 in the Client-Initiated Key Update.

Due to security issue

**Comment by rikard-sics** [comment]
We can raise the general problem related to OSCORE during the London meeting.

**Comment by rikard-sics** [comment]
Feedback from IETF 115 London CoRE session on Monday November 7:
Carsten: _Good thing to do to send Partial IV again._
Christian: _To detail why I don't think that this is just "an ad-hoc fix": I keep saying that you MUST ONLY EVER send a response on the piggy-back nonce if you just removed that number from that replay window for the key you're responding with. (Admittedly, that last detail I'm only adding since reading this...)._

**Comment by rikard-sics** [comment]
To comply with this in a generic way we can apply the same fix to the server-initiated version

See also issue #58

**Comment by marco-tiloca-sics** [comment]
Closed by https://github.com/core-wg/oscore-key-update/commit/645a6d80866d54c2552d8c01ff0838be5c343b96
