### ISSUE TITLE
Preserve observations following an update of updating OSCORE IDs alone

### ISSUE THREAD

**Issue by rikard-sics** [core-wg/oscore-key-update#65]
Similar approach to Group OSCORE be used. Meaning remembering the client's Sender ID in the registration request.

**Comment by rikard-sics** [comment]
Is it a problem in the first place? (request_kid is in the external_aad)

Worth doing it, or refer to use of KUDOS?

**Comment by rikard-sics** [comment]
May be simpler to forget the observations.

**Comment by rikard-sics** [comment]
Since we never reassign old IDs, observations can continue. (Until KUDOS is executed).

**Comment by marco-tiloca-sics** [comment]
Closed by https://github.com/core-wg/oscore-key-update/commit/d9773f5e53494e67d47938a5066f0a35df230873
