### ISSUE TITLE
Provide examples for KUDOS messages sizes (added overhead)

### ISSUE THREAD

**Issue by rikard-sics** [core-wg/oscore-key-update#75]
Give some calculations to show examples of typical sizes for the KUDOS messages. Either the total size, or the added overhead that usage of KUDOS produces.

**Comment by marco-tiloca-sics** [comment]
Closed by https://github.com/core-wg/oscore-key-update/commit/8520fb5df0db7c1eb0f10079dce794864ce5a66e
