### ISSUE TITLE
Does Request #1 need to target a KUDOS resource, or any resource (forward flow)

### ISSUE THREAD

**Issue by rikard-sics** [core-wg/oscore-key-update#83]
Meaning can the Request #1 be actionable? (Possibly only if idempotent)

**Comment by rikard-sics** [comment]
Option 1: Go for Appendix B.2 approach: Meaning the client can target any existing resource. But then the server cannot act on this request, and should respond with a 4.01, with no payload. Client must ignore any payload in response.

Option 2: Enforce that the client must send the request to a dedicated KUDOS resource, that doesn't produce a payload or act on requests. This may require that the KUDOS resource interacts with methods within the OSCORE-related code. Alternatively the OSCORE-related code can be aware of which resources are "KUDOS resources".

**Comment by rikard-sics** [comment]
We can present what Appendix B.2 does and present Option 2 as the alternative.

**Comment by marco-tiloca-sics** [comment]
[1] mentions this topic and puts it in relation with issue #85 

[1] https://mailarchive.ietf.org/arch/msg/core/vSF5Mqo9LAioEM0AUEfoxxl7Zv4/

**Comment by rikard-sics** [comment]
This should now be taken care of with commit ffe05281f3d74fd464643056dd3ad88256db5c73 for closing issue #93
